### PR TITLE
Add some features to code builder

### PR DESCRIPTION
**Pull request by uWynell**
### What I did:
- Rewrote found classes into ES6 standard
- Added some new handy methods to CodeBuilder class, so that you can control indentation easier (an example will in another pull request with Reqwest target for Rustm which I'll upload later)
- Added `%q` (escape quotes and other special characters) and `%v` (stringify json) options in format. Before each call used `%s`, so in many cases it led to unescaped quotes.
- Tried to replace `%s` to `%q` where seems appropriate. Used VSCode replace functionality and Regex, tried to do as accurately, as I can. Still passing tests, so I hope I did it completely. Won't be worse in any case.

### CODE REVIEW

**Comment by uWynell** [comment]
I will upload Reqwest target for Rust when it will be 100% clear whether this pull request is going to be merged or not

**Comment by uWynell** [comment]
I see. Should I close this pull request, rework these features and make a new PR?
I'd like to discuss each feature separately:
1. This update fixes unescaped quotes (although by changing some `%s`-es to `%q`-s in the target files). Should I undo that as well?
2. The update with adding `%q` and `%v` format rules - do I understand correctly, that you suggest to still implement it (it's a few lines of code and a new file), but without moving the whole CodeBuilder class to ES6?
3. The same question, but about `indent`, `unindent` and `reindent` methods. Can I still add them to the "native" `CodeBuilder`, or do I better move them inside the Rust target, where I actively use them?

**Comment by pimterry** [comment]
> The update with adding %q and %v format rules - do I understand correctly, that you suggest to still implement it (it's a few lines of code and a new file), but without moving the whole CodeBuilder class to ES6?

> The same question, but about indent, unindent and reindent methods. Can I still add them to the "native" CodeBuilder, or do I better move them inside the Rust target, where I actively use them?

In both cases, yes you can still implement them in the CodeBuilder, that's fine! Just avoid converting the whole thing or making unnecessary changes if possible. Adding methods isn't likely to cause conflicts (or those conflicts will be easy to fix). Modifying existing methods etc is much more likely to cause conflicts, so we should minimize that, where possible.

> This update fixes unescaped quotes (although by changing some %s-es to %q-s in the target files). Should I undo that as well?

Good point! I think for places where the quotes and useful and currently missing, yes, let's add the fix to change them to `%q`, that's worth fixing. If the quotes are already there, so we wouldn't actually change anything about the output, don't bother.

> Should I close this pull request, rework these features and make a new PR?

Up to you - I'm fine with editing this one, or a new PR. It would be nice to end up with a clean git history in the end either way though. If you're happy rebasing and squashing you can do that within this PR and force-update it, or you can make a totally new branch and build a new set of changes there if that's easier, totally up to you.

Does that all make sense? Let me know if you have any other questions.

**Comment by uWynell** [comment]
`%q` does **not** add quotes, it only escapes some characters (like `\n` and `"`) in the string. So it is only useful **inside** quotes **inside** generated code lines (exactly where I only added them), so that, for example:
```js
// this
format('Hello("%q")', '{ "world": true }')
// would produce:
// Hello("{ \"world\": true }")

//while this:
format('Hello("%s")', '{ "world": true }')
// would produce:
// Hello("{ "world": true }")
// you see this breaks the string
```
For example, check out [https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA](sec-ch-ua) header; it actually contains quotes and is present in many (if not all) requests from my chrome browser.

So I can completely remain this commit, right?

**Comment by pimterry** [comment]
> So I can keep this commit, right?

Sure - we can include this in the CodeBuilder and format helpers, that's fine, as long as it doesn't require rewriting the whole class completely. Skimming through the code, it looks like we should _not_ keep most of the snippet changes to use %q though, because they're not really necessary (e.g. because they're string interpolations of HTTP methods, protocols or hostnames, none of which can ever contain quotes or newlines). Happy to keep any where there are valid values of the string that genuinely might need escaping, e.g. header values and bodies, or if it's just not clear either way.

The overall idea is that we should make changes here that make real valuable improvements to the snippet output. I just want to remove/shrink all changes that are optional (i.e. which don't ever change the output or support future changes that do) so we can minimize merge conflicts in future.

Converting to ES6 classes is optional, and doesn't change output, so we should remove that. It looks most of the changes of existing snippets to %q are optional and don't change output (e.g. all the tests still pass testing against the previous output) so we should skip most of those too. However, adding the CodeBuilder logic to allow using %q and the new indent methods isn't optional, because that's required to implement your Reqwest PR. Does that make more sense?

**Comment by pimterry** [comment]
> Should I change them back to %s, add a new test case with quotes everywhere they might be met in real requests, and then change to %q-s where the test fails? :\

Up to you! If you have time and you're interested in doing that, feel free. If it's difficult to do that though, you're welcome to just revert those changes instead, and we can add them in later incrementally as we spot specific cases where this matters.

**Comment by uWynell** [comment]
Ok

**Pull request closed without merging**
